openapi: 3.0.0
info:
  contact:
    email: support@wishlist.example.com
    name: API Support
  description: >-
    A RESTful API for managing wish lists, gift items, and reservations.

    Features include user authentication, wish list management, gift item
    tracking, and reservation system.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Wish List API
  version: '1.1'
paths:
  /auth/change-email:
    $ref: paths/auth_change-email.yaml
  /auth/change-password:
    $ref: paths/auth_change-password.yaml
  /auth/exchange:
    $ref: paths/auth_exchange.yaml
  /auth/login:
    $ref: paths/auth_login.yaml
  /auth/logout:
    $ref: paths/auth_logout.yaml
  /auth/mobile-handoff:
    $ref: paths/auth_mobile-handoff.yaml
  /auth/oauth/facebook:
    $ref: paths/auth_oauth_facebook.yaml
  /auth/oauth/google:
    $ref: paths/auth_oauth_google.yaml
  /auth/refresh:
    $ref: paths/auth_refresh.yaml
  /auth/register:
    $ref: paths/auth_register.yaml
  /guest/reservations:
    $ref: paths/guest_reservations.yaml
  /healthz:
    $ref: paths/healthz.yaml
  /images/upload:
    $ref: paths/images_upload.yaml
  /items:
    $ref: paths/items.yaml
  /items/{id}:
    $ref: paths/items_{id}.yaml
  /items/{id}/mark-purchased:
    $ref: paths/items_{id}_mark-purchased.yaml
  /items/stats:
    $ref: paths/items_stats.yaml
  /protected/account:
    $ref: paths/protected_account.yaml
  /protected/export-data:
    $ref: paths/protected_export-data.yaml
  /protected/profile:
    $ref: paths/protected_profile.yaml
  /public/reservations/list/{slug}/item/{itemId}:
    $ref: paths/public_reservations_list_{slug}_item_{itemId}.yaml
  /public/reservations/wishlist/{wishlistId}/item/{itemId}:
    $ref: paths/public_reservations_wishlist_{wishlistId}_item_{itemId}.yaml
  /public/wishlists/{slug}:
    $ref: paths/public_wishlists_{slug}.yaml
  /public/wishlists/{slug}/gift-items:
    $ref: paths/public_wishlists_{slug}_gift-items.yaml
  /reservations/user:
    $ref: paths/reservations_user.yaml
  /reservations/wishlist-owner:
    $ref: paths/reservations_wishlist-owner.yaml
  /wishlists:
    $ref: paths/wishlists.yaml
  /wishlists/{id}:
    $ref: paths/wishlists_{id}.yaml
  /wishlists/{id}/items:
    $ref: paths/wishlists_{id}_items.yaml
  /wishlists/{id}/items/{itemId}:
    $ref: paths/wishlists_{id}_items_{itemId}.yaml
  /wishlists/{id}/items/{itemId}/mark-reserved:
    $ref: paths/wishlists_{id}_items_{itemId}_mark-reserved.yaml
  /wishlists/{id}/items/new:
    $ref: paths/wishlists_{id}_items_new.yaml
servers:
  - url: //localhost:8080/api
components:
  securitySchemes:
    BearerAuth:
      description: Type "Bearer" followed by a space and JWT token.
      in: header
      name: Authorization
      type: apiKey
